### ISSUE TITLE
Improve Turtle Scute Drops

### ISSUE THREAD

**Issue by sleepylessons** [sleepylessons/NetherAnarchy#10]
## Short overview of the issue
Because of Mob Limits, it is very difficult to have a large group of Turtles or Baby Turtles in one place. This severely limits the amount of scutes that can be collected over time, drastically lower than what is possible in Vanilla or even on other servers.

We need to add a patch to NetherAnarchyFarms plugin, similar to the logic we have to make Sheep drop more wool, or mobs drop more items when killed, to make baby turtles drop more scutes, to compensate for the low mob limits on turtles. We can also consider increasing limits on Turtles slightly to compensate further.

## Steps to reproduce the issue (describe how you can cause this issue to happen)
Try to have a scute farm, lol

## Is this issue new / recently noticed, or something that's been happening for a while?
Happening for a long time

**Comment by rawora-rg** [comment]
Done :)
