### ISSUE TITLE
Mutiple votes for NA, /stick reward can be lost

### ISSUE THREAD

**Issue by 0-0-6** [sleepylessons/NetherAnarchy#11]
## Short overview of the issue

Voting at multiple sites for NA in a short amount of time, you can miss the /stick gift. ... or I'm confused at how to redeem /stick

## Steps to reproduce the issue (describe how you can cause this issue to happen)
1) Vote for NA at multiple sites within a short timeframe (5 - 10 mins)
2) See a number of responses come in for votes in chat, including one in the middle that mentions you got the /stick command
3) type in /stick
4) I assume it should give you the stick or open up the gift menu, or given the stick but it just was a short blurb on what /stick was. 

## Is this issue new / recently noticed, or something that's been happening for a while?
I've only gotten the /stick notice once so IDK how long it's been happening. 

## Screenshots of the issue, if relevant
No screenshots taken

**Comment by rawora-rg** [comment]
Hey,

the /stick command serves only as a short explanation about what the stick is and how to get it

You don't have to actively execute anything yourself, if you vote and happen to get the stick, it will be automatically put into your inventory. Maybe your inventory was full?

The chance of getting one is very low too

Next time you see the message, have an empty inventory and still didn't get the stick, please report back with an approximate time when this occurred :)

Thanks

**Comment by 0-0-6** [comment]
oops and rodger that. I probably had a full inventory and was expecting something like /gift
