### ISSUE TITLE
Trying to swim through or elytra through 1 block tall spaces causes you to spam out

### ISSUE THREAD

**Issue by tinmarr** [sleepylessons/NetherAnarchy#21]
## Short overview of the issue
Title says it all (let me know if it doesn't make sense)

## Steps to reproduce the issue (describe how you can cause this issue to happen)
Try to swim through a one-block gap. It doesn't work. You get rubberbanded.

## Is this issue new / recently noticed, or something that's been happening for a while?
It's been happening for a couple months

**Comment by hyde103** [comment]
Try turning off no fall. I was having this issue aswell, and no fall hardly helps when you are elytra flying anyways (at least in my experience I still take fall damage when landing most of the time with it on).

**Comment by tinmarr** [comment]
It still bugs you out when you're swimming. (I tested this on a vanilla client)

**Comment by tinmarr** [comment]
Seems Fixed...
