### ISSUE TITLE
Add command that allows players to mute the public chat in-game.

### ISSUE THREAD

**Issue by Buckeye12** [sleepylessons/NetherAnarchy#22]
**Is your feature request related to a problem? Please describe.**
No. This is a quality of life feature and it is not urgent.

**Describe the solution you'd like**
* By executing the command in-game, the main chat will become temporarily muted until the command is executed again.
* Players would still be able to use commands, party chat, and whispers.
* Syntax would look something like: `/togglegchat` -> `General chat is now on.` or `General chat is now off.`

**Quick links**
* This was a feature on destroymc.net (1.15.2 anarchy) and is currently a feature on limitedsurvival.com (1.16.5 anarchy).
* limitedsurvival.com chat plugin repository:
[limitedsurvival/SimpleMessage](https://github.com/limitedsurvival/SimpleMessage)
[CommandToggleChat.java](https://github.com/limitedsurvival/SimpleMessage/blob/master/src/main/java/lol/hyper/simplemessage/commands/CommandToggleChat.java)

**Comment by sleepylessons** [comment]
Your client can do this on its own. Here's a guide on how to do it:

https://gaming.stackexchange.com/questions/184334/how-do-i-hide-chat-on-minecraft

Sorry to shoot it down, I'm sure some people would find it useful, but the less code we have to maintain the better, and in this case there are built-in alternatives to accomplish the same thing so this feature would be a bit redundant in my opinion.

**Comment by Buckeye12** [comment]
From my experience, it's not possible to see party chat and dms with that turned off but I respect the discussion.
