### ISSUE TITLE
Add /report or /issue command

### ISSUE THREAD

**Issue by sleepylessons** [sleepylessons/NetherAnarchy#7]
**Is your feature request related to a problem? Please describe.**
I'd like people to have an easy way to get to this GitHub from in-game so they can report issues or suggest features without having to search around the discord or elsewhere.

**Describe the solution you'd like**
When someone runs /report or /issue they should get a link to this GitHub, much like our /discord or /website commands work right now.

**Comment by rawora-rg** [comment]
Done :)

**Added Command**: 
/issue _(alias: /report)_


**Preview:**
![image](https://user-images.githubusercontent.com/58186033/119908153-44f40b80-bf52-11eb-9d80-89e38036f564.png)
