### ISSUE TITLE
Allow Donors to "recharge" their Megaphone by Voting

### ISSUE THREAD

**Issue by sleepylessons** [sleepylessons/NetherAnarchy#9]
**Is your feature request related to a problem? Please describe.**
Donors currently are limited to 1 megaphone every 6 hours and have very little incentive to vote.

**Describe the solution you'd like**
If a Donor votes for the server, and have used their Megaphone already for the 6 hour period, it should automatically "recharge" their megaphone and allow them to use it again.

This will give Donors another incentive to vote without changing the game itself, and allow them to use the feature more frequently, a win-win for everyone. We've not added new Donor features for a while so we should give them some love.

**Comment by sleepylessons** [comment]
@rawora-rg I've thought of a couple ways we might be able to do this. My voting plugin (which I believe you have access to the source of, but don't really need for this purpose) pulls data from the Database every 10 minutes to see who needs rewards. I can set rewards in config on the plugin, that run commands.

Maybe what we need to do is just create a command that allows the Megaphone to be recharged, that can only be run by admins. Something like /rechargemegaphone <playername>. When the command is run it should check if the player's megaphone is used; if not, then it should do nothing; if it is used, it should reset their cooldown.

It doesn't matter if it's run for non-donors because they don't have access to the /megaphone command anyway.

**Comment by rawora-rg** [comment]
Done :)
Send you the details in Discord
